# .sqa/config.yml - jenkins-pipeline-library configuration file
config:
  credentials:
    - id: AIOS-registry-credentials
      username_var: JPL_DOCKERUSER
      password_var: JPL_DOCKERPASS

environment:
  JPL_DOCKERPUSH: "ai4os-federated-server"
  JPL_DOCKERFORCEREBUILD: "True"
  LANG: C.UTF-8

sqa_criteria:
  qc_style:
    repos:
      ai4os-federated-server:
        container: thisrepo-testing
        tox:
          tox_file: tox.ini
          testenv:
            - qc.sty
#  qc_coverage:
#    repos:
#      ai4os-federated-server:
#        container: thisrepo-testing
#        tox:
#          tox_file: tox.ini
#          testenv:
#            - qc.cov
  qc_security:
    repos:
      ai4os-federated-server:
        container: thisrepo-testing
        tox:
          tox_file: tox.ini
          testenv:
            - qc.sec

timeout: 600
