version: "3.6"

services:
  thisrepo-testing:
    image: "indigodatacloud/ci-images:python3.10"
    container_name: "${BUILD_TAG}"
    hostname: "${BUILD_TAG}"
    working_dir: /srv
    command: >
      sh -c "git config --global --add safe.directory /srv &&
             tail -f /dev/null"
    volumes:
      - type: bind
        source: ./
        target: /srv

  ai4os-federated-server:
     build:
        context: "."
        dockerfile: "Dockerfile"
        args:
          branch: ${GIT_BRANCH}
     image: "${APP_DOCKER_IMAGE}"